### ISSUE TITLE
dx-menu internationalization

### ISSUE THREAD

**Issue by Like2Read** [GoshaFighten/dx-ngx-application#182]
Thanks for this great example.
But I have some kind of issue, not with the project but with DxMenuComponent translation.
I've added menu
<dx-menu class="dx-menu-xd"
            #menu
            [dataSource]="navigationMenu"
            displayExpr="title"
            orientation="horizontal"
            submenuDirection="auto"
            [hideSubmenuOnMouseLeave]="false"
            (onItemClick)="itemClick($event)"></dx-menu>

And there is not translation there, just an original text. :(((

Thank you for your help in advance!!!
Best regards,
Alex

**Comment by GoshaFighten** [comment]
I suggest you specify the menu item template where you can use the ngx-translate pipe to localize menu items. See the [plunk](https://plnkr.co/edit/nwB8SVaSyh1EkIZZZ03m?p=preview) that illustrates this.

``` HTML
<div class="dx-item-content dx-menu-item-content dx-menu-item-has-text" *dxTemplate="let data of 'item'">
  <span class="dx-menu-item-text">{{data.name | translate}}</span>
</div>
```

**Comment by Like2Read** [comment]
Thank you very much!
It works just fine.

**Comment by GoshaFighten** [comment]
You are welcome!
